import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // Streak achievements
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day exercise streak',
    icon: '🔥',
    category: 'streak',
    rarity: 'common',
    requirement: { type: 'streak', days: 7 },
    reward: { xp: 100, badge: 'week-warrior' }
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    description: 'Maintain a 30-day exercise streak',
    icon: '🏆',
    category: 'streak',
    rarity: 'rare',
    requirement: { type: 'streak', days: 30 },
    reward: { xp: 500, badge: 'monthly-master' }
  },
  {
    id: 'streak_100',
    name: 'Century Club',
    description: 'Maintain a 100-day exercise streak',
    icon: '💎',
    category: 'streak',
    rarity: 'legendary',
    requirement: { type: 'streak', days: 100 },
    reward: { xp: 2000, badge: 'century-club' }
  },

  // Milestone achievements
  {
    id: 'breaks_100',
    name: 'Break Master',
    description: 'Complete 100 exercise breaks',
    icon: '💯',
    category: 'milestone',
    rarity: 'common',
    requirement: { type: 'count', action: 'break', count: 100 },
    reward: { xp: 150, badge: 'break-master' }
  },
  {
    id: 'exercises_500',
    name: 'Exercise Enthusiast',
    description: 'Complete 500 exercises',
    icon: '🎯',
    category: 'milestone',
    rarity: 'rare',
    requirement: { type: 'count', action: 'exercise', count: 500 },
    reward: { xp: 800, badge: 'exercise-enthusiast' }
  },

  // Special achievements
  {
    id: 'morning_7',
    name: 'Morning Glory',
    description: 'Exercise in the morning for 7 consecutive days',
    icon: '🌅',
    category: 'special',
    rarity: 'rare',
    requirement: { type: 'time-based', time: 'morning', days: 7 },
    reward: { xp: 200, badge: 'morning-glory' }
  },
  {
    id: 'night_owl',
    name: 'Night Owl Health',
    description: 'Exercise after 10 PM 10 times',
    icon: '🌙',
    category: 'special',
    rarity: 'epic',
    requirement: { type: 'time-based', time: 'night', count: 10 },
    reward: { xp: 300, badge: 'night-owl' }
  }
];

export const LEVELS = [
  { level: 1, name: 'Code Newbie', xpRequired: 0, icon: '🌱' },
  { level: 2, name: 'Alert Coder', xpRequired: 100, icon: '⚡' },
  { level: 3, name: 'Stretch Master', xpRequired: 250, icon: '🧘' },
  { level: 4, name: 'Stretch Master', xpRequired: 375, icon: '🧘' },
  { level: 5, name: 'Healthy Coder', xpRequired: 500, icon: '💪' },
  { level: 6, name: 'Healthy Coder', xpRequired: 700, icon: '💪' },
  { level: 7, name: 'Healthy Coder', xpRequired: 900, icon: '💪' },
  { level: 8, name: 'Healthy Coder', xpRequired: 1100, icon: '💪' },
  { level: 9, name: 'Healthy Coder', xpRequired: 1300, icon: '💪' },
  { level: 10, name: 'Wellness Warrior', xpRequired: 1500, icon: '⚔️' },
  { level: 11, name: 'Wellness Warrior', xpRequired: 1800, icon: '⚔️' },
  { level: 12, name: 'Wellness Warrior', xpRequired: 2100, icon: '⚔️' },
  { level: 13, name: 'Wellness Warrior', xpRequired: 2400, icon: '⚔️' },
  { level: 14, name: 'Wellness Warrior', xpRequired: 2700, icon: '⚔️' },
  { level: 15, name: 'Balance Champion', xpRequired: 3000, icon: '⚖️' },
  { level: 16, name: 'Balance Champion', xpRequired: 3400, icon: '⚖️' },
  { level: 17, name: 'Balance Champion', xpRequired: 3800, icon: '⚖️' },
  { level: 18, name: 'Balance Champion', xpRequired: 4200, icon: '⚖️' },
  { level: 19, name: 'Balance Champion', xpRequired: 4600, icon: '⚖️' },
  { level: 20, name: 'Zen Master', xpRequired: 5000, icon: '🧘‍♂️' },
  { level: 21, name: 'Zen Master', xpRequired: 5500, icon: '🧘‍♂️' },
  { level: 22, name: 'Zen Master', xpRequired: 6000, icon: '🧘‍♂️' },
  { level: 23, name: 'Zen Master', xpRequired: 6500, icon: '🧘‍♂️' },
  { level: 24, name: 'Zen Master', xpRequired: 7000, icon: '🧘‍♂️' },
  { level: 25, name: 'Zen Master', xpRequired: 7500, icon: '🧘‍♂️' },
  { level: 26, name: 'Zen Master', xpRequired: 8000, icon: '🧘‍♂️' },
  { level: 27, name: 'Zen Master', xpRequired: 8500, icon: '🧘‍♂️' },
  { level: 28, name: 'Zen Master', xpRequired: 9000, icon: '🧘‍♂️' },
  { level: 29, name: 'Zen Master', xpRequired: 9500, icon: '🧘‍♂️' },
  { level: 30, name: 'Health Guru', xpRequired: 10000, icon: '🌟' },
  { level: 31, name: 'Health Guru', xpRequired: 10750, icon: '🌟' },
  { level: 32, name: 'Health Guru', xpRequired: 11500, icon: '🌟' },
  { level: 33, name: 'Health Guru', xpRequired: 12250, icon: '🌟' },
  { level: 34, name: 'Health Guru', xpRequired: 13000, icon: '🌟' },
  { level: 35, name: 'Health Guru', xpRequired: 13750, icon: '🌟' },
  { level: 36, name: 'Health Guru', xpRequired: 14500, icon: '🌟' },
  { level: 37, name: 'Health Guru', xpRequired: 15250, icon: '🌟' },
  { level: 38, name: 'Health Guru', xpRequired: 16000, icon: '🌟' },
  { level: 39, name: 'Health Guru', xpRequired: 16750, icon: '🌟' },
  { level: 40, name: 'Health Guru', xpRequired: 17500, icon: '🌟' },
  { level: 41, name: 'Health Guru', xpRequired: 18250, icon: '🌟' },
  { level: 42, name: 'Health Guru', xpRequired: 19000, icon: '🌟' },
  { level: 43, name: 'Health Guru', xpRequired: 19750, icon: '🌟' },
  { level: 44, name: 'Health Guru', xpRequired: 20500, icon: '🌟' },
  { level: 45, name: 'Health Guru', xpRequired: 21250, icon: '🌟' },
  { level: 46, name: 'Health Guru', xpRequired: 22000, icon: '🌟' },
  { level: 47, name: 'Health Guru', xpRequired: 22750, icon: '🌟' },
  { level: 48, name: 'Health Guru', xpRequired: 23500, icon: '🌟' },
  { level: 49, name: 'Health Guru', xpRequired: 24250, icon: '🌟' },
  { level: 50, name: 'Immortal Developer', xpRequired: 25000, icon: '👑' },
  { level: 51, name: 'Immortal Developer', xpRequired: 26000, icon: '👑' },
  { level: 52, name: 'Immortal Developer', xpRequired: 27000, icon: '👑' },
  { level: 53, name: 'Immortal Developer', xpRequired: 28000, icon: '👑' },
  { level: 54, name: 'Immortal Developer', xpRequired: 29000, icon: '👑' },
  { level: 55, name: 'Immortal Developer', xpRequired: 30000, icon: '👑' },
  { level: 56, name: 'Immortal Developer', xpRequired: 31000, icon: '👑' },
  { level: 57, name: 'Immortal Developer', xpRequired: 32000, icon: '👑' },
  { level: 58, name: 'Immortal Developer', xpRequired: 33000, icon: '👑' },
  { level: 59, name: 'Immortal Developer', xpRequired: 34000, icon: '👑' },
  { level: 60, name: 'Immortal Developer', xpRequired: 35000, icon: '👑' },
  { level: 61, name: 'Immortal Developer', xpRequired: 36500, icon: '👑' },
  { level: 62, name: 'Immortal Developer', xpRequired: 38000, icon: '👑' },
  { level: 63, name: 'Immortal Developer', xpRequired: 39500, icon: '👑' },
  { level: 64, name: 'Immortal Developer', xpRequired: 41000, icon: '👑' },
  { level: 65, name: 'Immortal Developer', xpRequired: 42500, icon: '👑' },
  { level: 66, name: 'Immortal Developer', xpRequired: 44000, icon: '👑' },
  { level: 67, name: 'Immortal Developer', xpRequired: 45500, icon: '👑' },
  { level: 68, name: 'Immortal Developer', xpRequired: 47000, icon: '👑' },
  { level: 69, name: 'Immortal Developer', xpRequired: 48500, icon: '👑' },
  { level: 70, name: 'Immortal Developer', xpRequired: 50000, icon: '👑' },
  { level: 71, name: 'Immortal Developer', xpRequired: 52000, icon: '👑' },
  { level: 72, name: 'Immortal Developer', xpRequired: 54000, icon: '👑' },
  { level: 73, name: 'Immortal Developer', xpRequired: 56000, icon: '👑' },
  { level: 74, name: 'Immortal Developer', xpRequired: 58000, icon: '👑' },
  { level: 75, name: 'Master Programmer', xpRequired: 60000, icon: '🤴' },
  { level: 76, name: 'Master Programmer', xpRequired: 63000, icon: '🤴' },
  { level: 77, name: 'Master Programmer', xpRequired: 66000, icon: '🤴' },
  { level: 78, name: 'Master Programmer', xpRequired: 69000, icon: '🤴' },
  { level: 79, name: 'Master Programmer', xpRequired: 72000, icon: '🤴' },
  { level: 80, name: 'Master Programmer', xpRequired: 75000, icon: '🤴' },
  { level: 81, name: 'Master Programmer', xpRequired: 78000, icon: '🤴' },
  { level: 82, name: 'Master Programmer', xpRequired: 81000, icon: '🤴' },
  { level: 83, name: 'Master Programmer', xpRequired: 84000, icon: '🤴' },
  { level: 84, name: 'Master Programmer', xpRequired: 87000, icon: '🤴' },
  { level: 85, name: 'Master Programmer', xpRequired: 90000, icon: '🤴' },
  { level: 86, name: 'Master Programmer', xpRequired: 95000, icon: '🤴' },
  { level: 87, name: 'Master Programmer', xpRequired: 100000, icon: '🤴' },
  { level: 88, name: 'Master Programmer', xpRequired: 105000, icon: '🤴' },
  { level: 89, name: 'Master Programmer', xpRequired: 110000, icon: '🤴' },
  { level: 90, name: 'Master Programmer', xpRequired: 115000, icon: '🤴' },
  { level: 91, name: 'Master Programmer', xpRequired: 120000, icon: '🤴' },
  { level: 92, name: 'Master Programmer', xpRequired: 126000, icon: '🤴' },
  { level: 93, name: 'Master Programmer', xpRequired: 132000, icon: '🤴' },
  { level: 94, name: 'Master Programmer', xpRequired: 138000, icon: '🤴' },
  { level: 95, name: 'Master Programmer', xpRequired: 144000, icon: '🤴' },
  { level: 96, name: 'Master Programmer', xpRequired: 150000, icon: '🤴' },
  { level: 97, name: 'Master Programmer', xpRequired: 156000, icon: '🤴' },
  { level: 98, name: 'Master Programmer', xpRequired: 162000, icon: '🤴' },
  { level: 99, name: 'Master Programmer', xpRequired: 170000, icon: '🤴' },
  { level: 100, name: 'Legendary Programmer', xpRequired: 180000, icon: '🤴' },
];
